{
    'rep_emissions' : ['CO2|Fossil Fuels and Industry|Energy Supply',
                       'CO2|Fossil Fuels and Industry|Energy Supply|Electricity',
                       'CO2|Fossil Fuels and Industry|Energy Supply|Non-electricity',
                       'CO2|Land Use',
                       'CO2|Avoided Deforestation',
                       'CO2|Land Use + Avoided Deforestation',
                       'GHG|International Trading System',
                       'GHG|Allowance Allocation',
                       'GHG','N2O','CH4',
                       'GHG|Abatement'],
    'rep_capacity':None,
    'rep_capital_cost':None,
    'rep_final_energy':None,
    'rep_lcoe':None,
    'rep_policy_cost':['Additional Total Energy System Cost',
                       'consumption Loss',
                       'gdp Loss',
                       'gdp Loss %'],
    'rep_price_emissions':None,
    'rep_price_energy':None,
    'rep_primary_energy': ['Total',
                           'Biomass',
                           'Biomass|Electricity',
                           'Biomass|Electricity|w/ CCS',
                           'Biomass|Energy Crops',
                           'Biomass|Modern',
                           'Biomass|Traditional',
                           'Coal',
                           'Coal|Electricity',
                           'Coal|Electricity|w/ CCS',
                           'Electricity',
                           'Fossil',
                           'Fossil|w/ CCS',
                           'Gas',
                           'Gas|Electricity',
                           'Gas|Electricity|w/ CCS',
                           'Hydro',
                           'Non-Biomass Renewables',
                           'Nuclear',
                           'Oil',
                           'Oil|Electricity',
                           'Other',
                           'Wind',
                           'Solar'],
    'rep_secondary_energy':['Total',
                            'Electricity',
                            'Electricity|Biomass',
                            'Electricity|Biomass|w/ CCS',
                            'Electricity|Coal',
                            'Electricity|Coal|w/ CCS',
                            'Electricity|Gas',
                            'Electricity|Gas|w/ CCS',
                            'Electricity|Hydro',
                            'Electricity|Non-Biomass Renewables',
                            'Electricity|Nuclear',
                            'Electricity|Oil',
                            'Electricity|Other',
                            'Gases',
                            'Liquids',
                            'Liquids|Biomass',
                            'Liquids|Biomass|1st Generation',
                            'Liquids|Biomass|Energy Crops',
                            'Liquids|Oil',
                            'Solids',
                            'Solids|Biomass',
                            'Solids|Coal',
                            'Electricity|Wind',
                            'Electricity|Solar'],
    'trade_emissions_value':None,
    'trade_emissions_volume':None,
    'trade_primary_energy_value':None,
    'trade_primary_energy_volume':None,
    'rep_consumption':None,
    'rep_gdp':None,
    'rep_population':None,
    'rep_interest_rate':None,
    'rep_gdp_pc':None,
    'rep_consumption_pc':None,
    'rep_intensity_energy_output':None,
    'rep_intensity_carbon_energy':None,
    'rep_intensity_carbon_output':None,
    'rep_forcing':None,
    'rep_concentration':None,
    'rep_temperature':None,
    'rep_trade_emissions_volume':None,
    'rep_trade_emissions_value':None,
    'rep_trade_energy_volume':None,
    'rep_trade_energy_value':None
}
