_regs = '(world|r5.*)'
#_regs = '(world|r5.*|china|usa|europe|india)'


def regify(l):
    return ('('+('|'.join([x.replace('|',r'\|') for x in l]))+')$')

filt_dict = {
    'db': [
           ['Carbon Sequestration', '(ccs|Land Use|Direct Air Capture)$', '(|Fossil|Biomass)$', '', _regs],
           ['Emissions', '(co2|ch4|n2o|kyoto gases|f-gases)$', r'(|AFOLU|Energy|Energy\|Supply\|Electricity)$', '', _regs],
           ['Secondary Energy$', '(|electricity|Gases|Hydrogen|Liquids|Solids)$', regify(['',
                                                                                                                         'Biomass',
        'Biomass|w/ CCS',
        'Biomass|w/o CCS',
        'Coal',
        'Coal|w/ CCS',
        'Coal|w/o CCS',
        'Gas',
        'Gas|w/ CCS',
        'Gas|w/o CCS',
        'Hydro',
        'Nuclear',
        'Oil',
        'Oil|w/ CCS',
        'Oil|w/o CCS',
        'Solar',
        'Wind']), '', _regs],
        ['Final Energy$', regify(['',
 'Electricity',
 'Gases',
 'Hydrogen',
 'Industry',
 'Liquids',
 'Residential and Commercial',
 'Solar',
 'Solids',
 'Transportation']), regify(['','biomass','coal','oil', 'Electricity',
    'Hydrogen',
    'Liquids',
    'Liquids|Biomass',
    'Liquids|Oil']), '', _regs],
        ['Price', regify(['carbon','primary energy', 'secondary energy']), regify(['',
        'Biomass',
        'Coal',
        'Gas',
        'Oil',
        'Electricity',
        'Hydrogen',
        'Liquids',
        'Liquids|Biomass',
        'Liquids|Oil']), '', _regs],
        ['Temperature', '', '', '', _regs],
 # ['Policy cost', '', '', '', '(world|china|usa|europe|india|r5.*)'],
           # ['Price', '((Primary|Secondary) Energy|Carbon)', '', '', '(world|china|usa|europe|india|r5.*)'],
           # ['Primary Energy',' ', '', '', '(world|china|usa|europe|india|r5.*)'],
           # ['Secondary Energy','', '', '', '(world|china|usa|europe|india|r5.*)'],
           # ['Final Energy','', '', '', '(world|china|usa|europe|india|r5.*)'],
           # ['Temperature','', '', '', '(world|china|usa|europe|india|r5.*)'],
           ],
}
