{
    'Q_EMI' : ["ch4",
               "ch4_ffi",
               "ch4_agr",
               # "ch4_wst",
               "co2",
               "co2ffi",
               "co2lu",
               # "co2peat",
               "f-gases",
               # "hfc",
               "kghg",
               "n2o",
               "n2o_ffi",
               "n2o_agr"],

    'Q_FUEL' : ["coal",
               "gas",
               "oil",
               "uranium",
                "advbiofuel",
                "trbiofuel",
                "trbiomass",
               "wbio"],

    'Q_EN' : ["el",
              "en",
              "nel",
              "neloil",
              "nelgas",
              "nelcoaltr",
              "nelcoalccs",
              "nelback",
              "neltrbiofuel",
              # "trad_cars",
              # "trad_stfr",
              # "plg_hbd_stfr",
              # "plg_hybrid",
              # "hybrid",
              # "hbd_stfr",
              # "edv",
              # "edv_stfr",
        "elgastr",
              "elbigcc",
              "elcigcc",
              "elgasccs"
              "elgastr",
              "elgas",
              "elhydro",
              "elnuclear",
              "eloil",
              "elpb",
              "elpc",
              "elwindon",
              "elwindoff",
              "elwind",
              "elpv",
              "elcsp",
              "elsolar"],

    'K_EN' : ["elgastr",
              "elhydro",
              "elnuclear",
              "eloil",
              "elpb",
              "elpc",
              "elwindon",
              "elwindoff",
              "elpv",
              "elcsp"],

    'Q_OUT' : ["coal",
               "gas",
               "oil",
               "uranium"],
    'FPRICE' : None,
    'MCOST_FUEL' : None,
    'Q' : ["y", ],
    'l' : None,
    'tpes' : None,    
}
