{
    'Q_EMI' : ["ch4",
               "ch4_ffi",
               "ch4_lu",
               "ch4_wst",
               "co2",
               "co2ffi",
               "co2lu",
               "co2peat",
               "f-gases",
               "hfc",
               "kghg",
               "n2o",
               "n2o_ffi",
               "n2o_lu"],

    'Q_PES' : ["coal",
               "gas",
               "oil",
               "uranium",
               "wbio"],

    'Q_EN' : ["elgastr",
              "elhydro",
              "elnuclear",
              "eloil",
              "elpb",
              "elpc",
              "elwindon",
              "elwindoff",
              "elwind",
              "elpv",
              "elcsp",
              "elsolar"],

    'K_EN' : ["elgastr",
              "elhydro",
              "elnuclear",
              "eloil",
              "elpb",
              "elpc",
              "elwindon",
              "elwindoff",
              "elpv",
              "elcsp"],

    'Q_OUT' : ["coal",
               "gas",
               "oil",
               "uranium"],
    'FPRICE' : None,
    'MCOST_FUEL' : None,
    'Q_FUEL': None,
    'Q' : ["y", ],
    'l' : None,
    'tpes' : None,    
}
